In [2]:
import numpy as np


In [3]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [4]:
x = np.zeros(4, dtype=int)
x

array([0, 0, 0, 0])

In [5]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),'formats':('U10','i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [6]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)


[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [7]:
data['name']


array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [8]:
data[0]

('Alice', 25, 55.)

In [9]:
data[-1]['name']


'Doug'

In [10]:
data['age']

array([25, 45, 37, 19])

In [11]:
# Get names where age is under 30
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [12]:
data_rec = data.view(np.recarray)
data_rec.age


array([25, 45, 37, 19])

In [13]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

163 ns ± 3.99 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
2.34 µs ± 59.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.08 µs ± 99.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
