In [1]:
import numpy as np 

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
x<3

array([ True,  True, False, False, False])

In [5]:
rng = np.random.RandomState(0)
x = rng.randint(10, size = (3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [6]:
x<3

array([[False,  True, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [7]:
np.count_nonzero(x<6)

8

In [8]:
np.sum(x<6)

8

In [10]:
np.sum(x<6, axis=0) #axis=1 =>row axis=0 =>column

array([2, 2, 2, 2])